version: "3.7"

services:
    postgres:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: api
            POSTGRES_USER: api
            POSTGRES_PASSWORD: api
        ports:
            - 5432:5432
    postgres_testing:
        image: postgres
        environment:
            POSTGRES_DB: api
            POSTGRES_USER: api
            POSTGRES_PASSWORD: api
        ports:
            - 5433:5432

volumes:
    postgres_data:
        driver: local
